### ISSUE TITLE
Problems while trying to make it run and reproduce results

### ISSUE THREAD

**Issue by lukasuz** [liuquande/SAML#1]
Hey, thanks for making the code public. Unfortunately, I ran into some problems while trying to reproduce the results. It seems like a .txt file has to be added to the dataset folder which is not included when downloading the processed nii dataset from [here](https://liuquande.github.io/SAML/):

```bash
File "main.py", line 148, in <module>
    main()
  File "main.py", line 135, in main
    train(model, saver, sess, train_file_list, test_file_list[0], args, resume_itr)
  File "/path/to/projects/SAML/train.py", line 21, in train
    batch_size=args.meta_batch_size, num_classes=args.n_class, shuffle=True)
  File "/path/to/projects/SAML/data_generator.py", line 38, in __init__
    self._read_txt_file()
  File "/path/to/projects/SAML/data_generator.py", line 79, in _read_txt_file
    with open(self.txt_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/path/to/data/HK_train_list'
```
The only change that I have made is to change the `main.py` so that `filelist_root` points to the .nii dataset folder. I am not sure whether I am missing the file somewhere. I can also not find a data prep script. Could you make the .txt list of the training images available or let us know how the .txt file has to be structured so that the training script runs?

Thanks!

**Comment by lukasuz** [comment]
I have implemented a little script which seems to do the job, if you are open to pull requests, please let me know. Otherwise, for people who are struggling with the same issue, the following code seems to generate the appropriate files:

```python
import argparse
import os

if __name__ == "__main__":
    desc = "Generates the necessary txt files for the data generator."
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('--path', type=str, default='../dataset', help='Path to the file root folder containig the data sets from several domains.')
    args = parser.parse_args()

    dirs = os.listdir(args.path)
    dirs = [dir for dir in dirs if os.path.isdir(os.path.join(args.path, dir))] # filter out potential non-directories
    for dir_path in dirs:
        file_paths = os.listdir(os.path.join(args.path, dir_path))
        file_paths = [file_paths for file_paths in file_paths if "nii.gz" in file_paths] # filter out potential unwanted files
        file_paths.sort()
        
        lines = []
        for i in range(0, len(file_paths), 2): # every second file is a segmentation mask
            img_path = os.path.join(args.path, dir_path, file_paths[i])
            mask_path = os.path.join(args.path, dir_path, file_paths[i + 1])
            line = img_path + ',' + mask_path + '\n'
            lines.append(line)

        file_list_path = os.path.join(args.path, dir_path + '_train_list')
        with open(file_list_path, "w") as file_list:
            file_list.writelines(lines)
```

**Comment by DrraBL** [comment]
Hi @lukasuz 
many thanks for sharing the code above. I am trying to reproduce the results but I got nothing and I wanted to use the datasets used in this work for that I wanted to load the data using the data_generator file. I have created an instance of data generator that takes as input one of the txt files but  I got an error of bad file descriptor. please have an idea about this error because I have checked the txt file and it contains paths to the images and their segmentation masks.
thank you in advance.
