### ISSUE TITLE
Dataset splits

### ISSUE THREAD

**Issue by JunMa11** [liuquande/SAML#2]
Dear @liuquande ,

Thanks for sharing the great work.

Could you please share the data split files in Table 2?

For example, in each Site, which cases are used as training/testing.

![image](https://user-images.githubusercontent.com/19947331/117459805-60d14680-af7e-11eb-9ce0-0e7243b5766e.png)

![image](https://user-images.githubusercontent.com/19947331/117459655-397a7980-af7e-11eb-9322-40cd2c4a6df4.png)

Best,
Jun

**Comment by liuquande** [comment]
Hi Jun,

Thanks for the interest.

We use all the data from each site for training for testing. 
Taking Site A as target domain for instance, we will use all data from site B-F for training and all data from site A for testing.

**Comment by JunMa11** [comment]
Hi @liuquande,

Thanks for your reply very much.

> Taking Site A as target domain for instance, we will use all data from site B-F for training and all data from site A for testing.

This is the intra-site setting, right?

Q1. How about the training and testing data in DeepAll setting?


> with some outlier cases excluded to provide general internal performance on each site

Q2. What are these outlier cases in each site?

Looking forward to your reply:)

Kindest regards,
Jun

**Comment by liuquande** [comment]
Hi Jun,

> Taking Site A as target domain for instance, we will use all data from site B-F for training and all data from site A for testing.

This denote the DeepAll setting actually, and the Intra-site setting denote training and testing on the same site.

For Q2, we notice that in Intra-site setting, sometimes the model developed on Site X may not perform well on certain testing case of Site X (with Dice less than 20% if I remembered correctly). We think the reason could be the distribution of that particular testing case may not fit well with the learned data distribution at Site X, and regard cases like that as outlier cases.

**Comment by JunMa11** [comment]
Hi @liuquande ,

Got it. Thanks for your kind reply very much.

**Comment by SakurajimaMaiii** [comment]
> 

Could you share which cases are exclueded?
Looking forwart to your reply.
