### ISSUE TITLE
Issue with the Three Categories of Labels in the Site B Preprocessed Dataset

### ISSUE THREAD

**Issue by XiudingCai** [liuquande/SAML#6]
I downloaded the dataset from the Google Drive link provided at https://liuquande.github.io/SAML/ and noticed that the site B dataset contains three distinct labels (0, 1, 2), which differs from the datasets of the other sites. How should I address this discrepancy?

Thank you for your attention and assistance in resolving this matter.

**Comment by YonghengSun1997** [comment]
I have the same problem, did you solve it?

**Comment by XiudingCai** [comment]
> I have the same problem, did you solve it?

Yes, you just need to change label 2 to 1.

**Comment by YonghengSun1997** [comment]
Thank you so much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiuding ***@***.***&gt;; 
发送时间: 2024年1月4日(星期四) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuquande/SAML] Issue with the Three Categories of Labels in the Site B Preprocessed Dataset (Issue #6)





  
I have the same problem, did you solve it?
  
Yes, you just need to change label 2 to 1.
